export const Sequence = {
  //loaded from midi file
  ticksPerQuarter: 480,
  timeSignatures: [{ time: 0, numerator: 4, denominator: 4 }],
  tempos: [{ time: 0, qpm: 120 }],
  notes: [
    {
      pitch: 72,
      velocity: 102,
      startTime: 0,
      endTime: 0.125,
      instrument: 0,
      // program: -1,
      isDrum: false,
    },
    {
      pitch: 74,
      velocity: 102,
      startTime: 0.125,
      endTime: 0.25,
      instrument: 0,
      // program: -1,
      isDrum: false,
    },
    {
      pitch: 76,
      velocity: 102,
      startTime: 0.25,
      endTime: 0.375,
      instrument: 0,
      // program: -1,
      isDrum: false,
    },
    {
      pitch: 77,
      velocity: 102,
      startTime: 0.375,
      endTime: 0.5,
      instrument: 0,
      // program: -1,
      isDrum: false,
    },
    {
      pitch: 79,
      velocity: 102,
      startTime: 0.5,
      endTime: 0.625,
      instrument: 0,
      // program: -1,
      isDrum: false,
    },
    {
      pitch: 81,
      velocity: 102,
      startTime: 0.625,
      endTime: 0.75,
      instrument: 0,
      // program: -1,
      isDrum: false,
    },
    {
      pitch: 83,
      velocity: 102,
      startTime: 0.75,
      endTime: 0.875,
      instrument: 0,
      // program: -1,
      isDrum: false,
    },
    {
      pitch: 84,
      velocity: 102,
      startTime: 0.875,
      endTime: 1,
      instrument: 0,
      // program: -1,
      isDrum: false,
    },
  ],
  totalTime: 1,
  sourceInfo: { encodingType: "MIDI", parser: "TONEJS_MIDI_CONVERT" },
};
